### ISSUE TITLE
HTTP 404 Error because of "get_video_info" requests [BUG]

### ISSUE THREAD

**Issue by Iamnotagenius** [pytube/pytube#1007]
I am using the latest version of pytube and still getting this error.

Http error "page not found' occurs as soon as I'm trying to use a Youtube object.
I've tried this with random videos.
Having done some debugging stuff, I figured out thar this is happening with urls which contains 'get_video_info?video_id=...'

The code snippet below is enough to cause an error:
link = 'https://www.youtube.com/watch?v=PEikGKDVsCc'
yt = pytube.YouTube(link)
print(yt.title)

**Output**
File "D:\Codes\Python\MusicDownloader\main.py", line 22, in <module>
    print(yt.title)
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\__main__.py", line 352, in title
    self._title = self.player_response['videoDetails']['title']
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\__main__.py", line 168, in player_response
    if isinstance(self.player_config_args["player_response"], str):
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\__main__.py", line 188, in player_config_args
    self._player_config_args = self.vid_info
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\__main__.py", line 279, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\__main__.py", line 109, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\request.py", line 54, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "d:\Codes\Python\MusicDownloader\venv\lib\site-packages\pytube\request.py", line 38, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 555, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**System information**
Python version: 3.9.0
Pytube version (I ran `print(pytube.__version__)` in python): 10.7.1
Command used to install pytube: python -m pip install git+https://github.com/pytube/pytube

**Comment by tfdahlin** [comment]
hi @Iamnotagenius, this bug was fixed in v10.8.2, please update pytube with `python -m pip install --upgrade pytube`

**Comment by Iamnotagenius** [comment]
> hi @Iamnotagenius, this bug was fixed in v10.8.2, please update pytube with `python -m pip install --upgrade pytube`

Well, I've tried both commands to upgrade pytube (from git and from pypi) and still getting this bug. I noticed that during installation pytube tells me its version is 10.8.3 but when I check it by `print(pytube.__version__)` it prints out 10.7.1.

**Comment by tfdahlin** [comment]
That probably means that you have an issue with your `PATH` variable. Do you have both python2 and python3 installed by chance? Or have you recently installed a new version of python? What can happen sometimes is a new installation will try to use the pip libraries from an old installation, while installing to a new directory. I would recommend uninstalling and reinstalling python, making sure to select the option to automatically set your `PATH` variable during installation.

**Comment by Iamnotagenius** [comment]
Ah yes, I messed up with the virtual environment which I set but completely forgot about, thanks.
