### ISSUE TITLE
[BUG]AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by yAmIZErO31** [pytube/pytube#1228]
**Before creating an issue**
I am on the latest version of pytube 11.0.2
my pip is at the latest version

**Describe the bug**
So i can not download any videos using stream() method, I faced this issue yesterday as well and found a solution to change something in the cipher.py line 293, i did that and it worked for the rest of the day fine, when i woke up and tried to test it again the same error occurred even tho the line was changed and it is still changed as it was 

**To Reproduce**
Please provide the following information:
- 'http://www.youtube.com/watch?v=UUGtYLqtaxc'
- ```        for url, song_data in urls:
            print(url)
            yt = YouTube(url)

            video = yt.streams.filter(only_audio=True).first()

            print(SAVE_PATH)
            out_file = video.download(SAVE_PATH)```

**Expected behavior**
Well it should download the video!

**Output**
```Ignoring exception in command play:
Traceback (most recent call last):
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\discord\ext\commands\core.py", line 179, in wrapped
    ret = await coro(*args, **kwargs)
  File "J:\PycharmProjects\MyWorkProjects\work\SadisticFairyFolder\SadisticFairyCogs\music.py", line 496, in play
    files = await loop.run_in_executor(None, self.download_spotify_urls, ctx.guild.id,
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "J:\PycharmProjects\MyWorkProjects\work\SadisticFairyFolder\SadisticFairyCogs\music.py", line 82, in download_spotify_urls
    video = yt.streams.filter(only_audio=True).first()
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\discord\ext\commands\bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\discord\ext\commands\core.py", line 916, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\discord\ext\commands\core.py", line 188, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'span'
```

**System information**
Please provide the following information:
- Python 3.9.1
-Pytube 11.0.2
- pip install git+https://github.com/baxterisme/pytube

**Comment by accj1990** [comment]
@nik1097 Hey I have encountered this problem reported by the noble colleague as well.

**Comment by yAmIZErO31** [comment]
Yes i have noticed many others encountered this kind of issue but when i tried the fixes they mentioned, it only worked for yesterday but it stopped today even tho the fixes have been done
one of the fixes was to change line 293 in cipher.py to name = "iha"
the other one was to change this `func_regex = re.compile(r"function\([^)]+\)")` to `func_regex = re.compile(r"function\([^)]*\)")` but it shows at me like this `func_regex = re.compile(r"function\([^)]?\)")` now

**Comment by accj1990** [comment]
@yAmIZErO31 I understand! We have to wait, I have already scoured the forum looking for the solution as well and have tried these possible solutions, without success here.

**Comment by yAmIZErO31** [comment]
> @yAmIZErO31 I understand! We have to wait, I have already scoured the forum looking for the solution as well and have tried these possible solutions, without success here.

yeah i do understand that, i was just panicked cause like i fixed that yesterday and it worked and errors got back again today lol

**Comment by nik1097** [comment]
Hey I will check this out and try to fix it, but I'm not sure if this repo is being maintained any longer :( 
My pull request for the previous bug is still pending review.

**Comment by yAmIZErO31** [comment]
> Hey I will check this out and try to fix it, but I'm not sure if this repo is being maintained any longer :( My pull request for the previous bug is still pending review.

oh that would be terrible if that happened but thanks, also worst-case-scenario that happened, would it be fine if i ask for a substitute recommendation? like to download youtube videos into mp3 files to a certain path


Thanks

**Comment by pyonic** [comment]
Same issue...
https://github.com/pytube/pytube/issues/1218 this solution doesnot worked on me(
Still got an error:

...code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

Cant figure out how to fix it, any other solutions please?

**Comment by a-l-e-k-k** [comment]
This is a duplicate of #1225. The temporary fix is to change the name from ' name = "iha" '   to   ' name = "jha" '

**Comment by FebOne1** [comment]
I notice that 'jha' works for some videos. But a new error occurs when I tried to download 
https://www.youtube.com/watch?v=-hLsqlKm-A4

![image](https://user-images.githubusercontent.com/98919618/152401306-ede778b4-b604-453d-b757-d86e058c0b71.png)

**Comment by irfanshadikofficial** [comment]
> Yes i have noticed many others encountered this kind of issue but when i tried the fixes they mentioned, it only worked for yesterday but it stopped today even tho the fixes have been done one of the fixes was to change line 293 in cipher.py to name = "iha" the other one was to change this `func_regex = re.compile(r"function\([^)]+\)")` to `func_regex = re.compile(r"function\([^)]*\)")` but it shows at me like this `func_regex = re.compile(r"function\([^)]?\)")` now


I just started learning pytube 6 hours ago. And have been facing the same problem with 'streams' . I also tried to change things on cypher.py like you that I found on stackoverflow but it didn't worked for me. 
 `Python 3.9.10 | pytube 11.0.2`
The error I'm getting is this :
`Traceback (most recent call last):       
  File "C:\Users\irfan\Documents\pytube\YouTube Video Downloader.py", line 6, in <module>
    print(yt.streams)
  File "C:\Users\irfan\.virtualenvs\pytube\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\irfan\.virtualenvs\pytube\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\irfan\.virtualenvs\pytube\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\irfan\.virtualenvs\pytube\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\irfan\.virtualenvs\pytube\lib\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\irfan\.virtualenvs\pytube\lib\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'`

**Comment by dradosevich** [comment]
So I am jumping in as I too just tried to start learning pytube today (bad day to start it seems), mostly so when a patch is pushed I will (hopefully) notice. I am running pytube 11.0.2 and python 3.8.10. setting the name variable in cipher.py seems to have worked for the first video I am testing with, I changed the code to: 

```
#name = re.escape(get_throttling_function_name(js))
name = "jha"
```

That seems to have done it without any of the regex changes. The fix worked for an entire playlist of videos to be downloaded

And editing to add that as of 2-4-22 this fix no longer works

**Comment by yAmIZErO31** [comment]
Well "jha" no longer works lol, it worked at first and everything going smoothly but yeah, it's temporary fix after all

**Comment by vishnudas-bluefox** [comment]
still, this bug irritates any solutions :( /?

**Comment by irfanshadikrishad** [comment]
Will it even get fixed ? I saw someone saying its a dead library.

**Comment by HusseinAoda2** [comment]
I have the same problem!
