### ISSUE TITLE
Ultra low speed (30 kB/s) to download audio (downloading of video not affected)

### ISSUE THREAD

**Issue by NannoSilver** [pytube/pytube#1489]
I am running Pytube 12.1.2 (without any modification) installed from https://pypi.org/  and Python 3.9.13.

The download of audio (eg.: itag = 140) is at around 30 kB/s while the downloading of video (itag = 18) the speed is above 10 MB/s.

The problem started 2 or 3 days ago progressively. Now almost all audio download have the speed issue.
I tried the download of audio of different videos, with different itags, with different operational systems (Linux and Windows) and using different IPs at my ending, and the problem repeats always.

Here is a code you can use to check the issue:
```
from pytube import YouTube
from pytube.cli import on_progress
import datetime


# two videos picked by random for testing only:
# youtube_episode_id = 'lOPxDEATfHA'  # 2:34 minutes long
youtube_episode_id = 'Q3ex2rqU2Ik'   # 13:07 minutes long

youtube_video = 'http://youtube.com/watch?v=' + youtube_episode_id


yt = YouTube(youtube_video, on_progress_callback=on_progress)

print(f'options for download: {yt.streams}')
print(f'---------------------------')

duration_seconds = YouTube(youtube_video).length
print(f'duration: {duration_seconds} seconds')

# itag = 18 # video 360 pixels (THIS DOWNLOAD AT HIGH SPEED)
itag = 140  # audio only (THIS DOWNLOAD AT AROUND 30 KB/SEC)

size_bytes = yt.streams.get_by_itag(itag).filesize
print(f'File size: {size_bytes} bytes')

stream = yt.streams.get_by_itag(itag)
print(f'Will start the download:')
time_before = datetime.datetime.utcnow()
stream.download(filename=f'{youtube_episode_id}.mp4', skip_existing=True, max_retries=2)
download_time = datetime.datetime.utcnow() - time_before
print(f'Downloading time: {download_time.total_seconds()} seconds')
print(f'Average speed:    {size_bytes/download_time.total_seconds()/1024} kB/s ')
```

I just run it and got the following result:
```
options for download: [<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="8fps" vcodec="mp4v.20.3" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="298" mime_type="video/mp4" res="720p" fps="60fps" vcodec="avc1.4d4020" progressive="False" type="video">, <Stream: itag="302" mime_type="video/webm" res="720p" fps="60fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="398" mime_type="video/mp4" res="720p" fps="60fps" vcodec="av01.0.08M.08" progressive="False" type="video">, <Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="397" mime_type="video/mp4" res="480p" fps="30fps" vcodec="av01.0.04M.08" progressive="False" type="video">, <Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="396" mime_type="video/mp4" res="360p" fps="30fps" vcodec="av01.0.01M.08" progressive="False" type="video">, <Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015" progressive="False" type="video">, <Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="395" mime_type="video/mp4" res="240p" fps="30fps" vcodec="av01.0.00M.08" progressive="False" type="video">, <Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c" progressive="False" type="video">, <Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="394" mime_type="video/mp4" res="144p" fps="30fps" vcodec="av01.0.00M.08" progressive="False" type="video">, <Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">, <Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">]
---------------------------
duration: 786 seconds
File size: 12724355 bytes
Will start the download:
Downloading time: 395.873896 seconds
Average speed:    31.38910662017356 kB/s 
```

Seems a change at Youtube (or a technical problem at Youtube).

Anybody else with this issue?

**Comment by starascendin** [comment]
ya it's been happening to me as well

**Comment by Smehnov** [comment]
Had same issue few days ago with some periods when download speed becomes fine

**Comment by DouglasRitter** [comment]
I have been having this same issue recently, and did a little bit of testing.  I found that I am having extremely slow speeds on anything but itag 18&22, all others, even if far lower bitrate run at a crawl.  I don't think this has to do directly with audio vs video, but something else related to the different streams.

**Comment by paavampayyan** [comment]
same issue happening to me. any way to fix this??

**Comment by kinkyninja** [comment]
same for me

**Comment by NannoSilver** [comment]
I did a set of testing for different itags, for the same video, and this is the download speed results I got at my ending:
``` 

------------------------------------------------------------------

itag:                               17
Video duration:                    153 seconds
File size:                   1,431,604 bytes
Downloading time:                76.83 seconds
Average speed:                   18.20 kB/s
------------------------------------------------------------------

itag:                               18
Video duration:                    153 seconds
File size:                  11,214,138 bytes
Downloading time:                 0.55 seconds
Average speed:               19,787.38 kB/s
------------------------------------------------------------------

itag:                               22
Video duration:                    153 seconds
File size:                  14,138,472 bytes
Downloading time:                 1.18 seconds
Average speed:               11,722.80 kB/s
------------------------------------------------------------------

itag:                               299
Video duration:                    153 seconds
FAILED FOR ITAG: 299
------------------------------------------------------------------

itag:                               303
Video duration:                    153 seconds
FAILED FOR ITAG: 303
------------------------------------------------------------------

itag:                               298
Video duration:                    153 seconds
FAILED FOR ITAG: 298
------------------------------------------------------------------

itag:                               302
Video duration:                    153 seconds
FAILED FOR ITAG: 302
------------------------------------------------------------------

itag:                               135
Video duration:                    153 seconds
File size:                   6,208,058 bytes
Downloading time:                77.19 seconds
Average speed:                   78.54 kB/s
------------------------------------------------------------------

itag:                               244
Video duration:                    153 seconds
File size:                   6,837,041 bytes
Downloading time:                77.01 seconds
Average speed:                   86.70 kB/s
------------------------------------------------------------------

itag:                               134
Video duration:                    153 seconds
File size:                   4,026,665 bytes
Downloading time:                76.98 seconds
Average speed:                   51.08 kB/s
------------------------------------------------------------------

itag:                               243
Video duration:                    153 seconds
File size:                   5,171,509 bytes
Downloading time:                76.96 seconds
Average speed:                   65.62 kB/s
------------------------------------------------------------------

itag:                               133
Video duration:                    153 seconds
File size:                   2,159,725 bytes
Downloading time:                77.04 seconds
Average speed:                   27.38 kB/s
------------------------------------------------------------------

itag:                               242
Video duration:                    153 seconds
File size:                   2,763,583 bytes
Downloading time:                77.03 seconds
Average speed:                   35.03 kB/s
------------------------------------------------------------------

itag:                               160
Video duration:                    153 seconds
File size:                   1,266,220 bytes
Downloading time:                77.19 seconds
Average speed:                   16.02 kB/s
------------------------------------------------------------------

itag:                               278
Video duration:                    153 seconds
File size:                   1,521,172 bytes
Downloading time:                77.96 seconds
Average speed:                   19.05 kB/s
------------------------------------------------------------------

itag:                               139
Video duration:                    153 seconds
File size:                     936,935 bytes
Downloading time:                77.09 seconds
Average speed:                   11.87 kB/s
------------------------------------------------------------------

itag:                               140
Video duration:                    153 seconds
File size:                   2,483,951 bytes
Downloading time:                76.83 seconds
Average speed:                   31.57 kB/s
------------------------------------------------------------------

itag:                               249
Video duration:                    153 seconds
File size:                     921,501 bytes
Downloading time:                76.74 seconds
Average speed:                   11.73 kB/s
------------------------------------------------------------------

itag:                               250
Video duration:                    153 seconds
File size:                   1,027,795 bytes
Downloading time:                76.93 seconds
Average speed:                   13.05 kB/s
------------------------------------------------------------------

itag:                               251
Video duration:                    153 seconds
File size:                   1,864,592 bytes
Downloading time:                76.76 seconds
Average speed:                   23.72 kB/s


```

**Comment by DouglasRitter** [comment]
@sukhoi47 Looks like our testing shows identical, so the question is, what is the difference between 18/22 and all other streams?

**Comment by ArtiiP** [comment]
yt-dlp have the same problem  (but it fixed now on master/daily build)

`https://github.com/yt-dlp/yt-dlp/issues/6369#issuecomment-1447763187`

**Comment by NannoSilver** [comment]
At [https://github.com/yt-dlp/yt-dlp/issues/6369#issuecomment-1447763187](https://github.com/yt-dlp/yt-dlp/issues/6369#issuecomment-1447763187) the guys are saying youtube is throttling and they developed a solution.

**Comment by geosp** [comment]
This node library works: https://github.com/fent/node-ytdl-core. There is also a cli utility `ytdl` that you can invoke via Python.  Is working for me so they must be doing something different.

**Comment by guillealonsobeltran** [comment]
Slow audio download is also happening to me

**Comment by joaomsimoes** [comment]
Using the itag 22 I'm able to download fast

**Comment by IbrahimLakhzine** [comment]
same here

**Comment by lolzhunter** [comment]
seems the only temp fix so far is to only allow itags 22 and 18?

**Comment by Gabeperson** [comment]
THIS FIX IS OUTDATED, LOOK AT https://github.com/pytube/pytube/pull/1575/files

Just throwing this out as a temporary fix until an actual patch is deployed. I'm not sure if this will work for all machines, but it worked on my home windows desktop and my ubuntu 20.04 VPS.

EDIT: Changed code to prevent truncation of large files

Note: If you just want the fix, scroll down to the heading text "The actual fix"

The problem:
According to people at yt-dlp at https://github.com/yt-dlp/yt-dlp/issues/6369#issuecomment-1447763187, this is caused by the "Range" header being used to throttle downloads. To circumvent this, we just put the range to the url itself instead of in the header.

Here is the time without the fix:
```
---------------------------
duration: 786 seconds
File size: 12724355 bytes
Will start the download:
Downloading time: 394.632464 seconds
Average speed:    31.487850248649334 kB/s 
```
and here is the time with the fix:
```
---------------------------
duration: 786 seconds
File size: 12724355 bytes
Will start the download:
Downloading time: 0.597 seconds
Average speed:    20814.284639342546 kB/s 
```

### The actual fix

Locate and open site-packages/pytube/request.py. Go to lines 156-162 which should look like this:
```            
             try:
                 response = _execute_request(
                     url,
                     method="GET",
                     headers={"Range": range_header},
                     timeout=timeout
                  )
```
and change it to this:
```            
             try:
                 response = _execute_request(
                     url+f"&range={downloaded}-{stop_pos}",
                         method="GET",
                         timeout=timeout
                  )
```
Then scroll down a bit until you see 
```            
             try:
                 content_range = response.info()["Content-Range"]
                 file_size = int(content_range.split("/")[1])
             except (KeyError, IndexError, ValueError) as e:
                 logger.error(e)
```
and change it to 
```            
             try:
                 resp = _execute_request(
                     url + f"&range={0}-{99999999999}",
                     method="GET",
                     timeout=timeout
                  )
                  content_range = resp.info()["Content-Length"]
                  file_size = int(content_range)
              except (KeyError, IndexError, ValueError) as e:
                  logger.error(e)
```

**Comment by tenflyingbricks** [comment]
This fix worked for me, thank you!

**Comment by guillealonsobeltran** [comment]
Wow, thank you so much! I was having a lot of trouble with this. This fix worked for me as well!

**Comment by sukhoi47** [comment]
> Just throwing this out as a temporary fix until an actual patch is deployed. I'm not sure if this will work for all machines, but it worked on my home windows desktop and my ubuntu 20.04 VPS.
> 
> Note: If you just want the fix, scroll down to the heading text "The actual fix"
> 
> The problem: According to people at yt-dlp at [yt-dlp/yt-dlp#6369 (comment)](https://github.com/yt-dlp/yt-dlp/issues/6369#issuecomment-1447763187), this is caused by the "Range" header being used to throttle downloads. To circumvent this, we just put the range to the url itself instead of in the header.
> 
> Here is the time without the fix:
> 
> ```
> ---------------------------
> duration: 786 seconds
> File size: 12724355 bytes
> Will start the download:
> Downloading time: 394.632464 seconds
> Average speed:    31.487850248649334 kB/s 
> ```
> 
> and here is the time with the fix:
> 
> ```
> ---------------------------
> duration: 786 seconds
> File size: 12724355 bytes
> Will start the download:
> Downloading time: 0.597 seconds
> Average speed:    20814.284639342546 kB/s 
> ```
> 
> ### The actual fix
> 
> Locate and open site-packages/pytube/request.py. Go to lines 156-162 which should look like this:
> 
> ```
>              try:
>                   response = _execute_request(
>                         url,
>                         method="GET",
>                         headers={"Range": range_header},
>                         timeout=timeout
>                   )
> ```
> 
> and change it to this:
> 
> ```
>              try:
>                   response = _execute_request(
>                         url+f"&range={downloaded}-{stop_pos}",
>                         method="GET",
>                         timeout=timeout
>                   )
> ```
> 
> Then scroll down a bit until you see
> 
> ```
>              try:
>                   content_range = response.info()["Content-Range"]
>                   file_size = int(content_range.split("/")[1])
>               except (KeyError, IndexError, ValueError) as e:
>                   logger.error(e)
> ```
> 
> and change it to
> 
> ```
>              try:
>                   content_range = response.info()["Content-Length"]
>                   file_size = int(content_range)
>               except (KeyError, IndexError, ValueError) as e:
>                   logger.error(e)
> ```

Great job!
Worked here too!

**Comment by NannoSilver** [comment]
Ops... too early to say that worked...

I applied the patch as explained by @Gabeperson [here](https://github.com/pytube/pytube/issues/1489#issuecomment-1452868684).

While downloading a large audio with itag = 140, the downloaded file is truncated to 9,00 MB (9.437.184 bytes).
I tried around 20 videos, and all came truncated.


Here is the modified code you can use to check the new issue:

EDIT: HERE IS THE CORRECT CODE
```
from pytube import YouTube
from pytube.cli import on_progress
import datetime


# video picked by random for testing only:

youtube_episode_id = 'DIVounDJzAk' #  1:49:39 long

youtube_video = 'http://youtube.com/watch?v=' + youtube_episode_id


yt = YouTube(youtube_video, on_progress_callback=on_progress)

print(f'options for download: {yt.streams}')
print(f'---------------------------')

duration_seconds = YouTube(youtube_video).length
print(f'duration: {duration_seconds} seconds')

itag = 140  # audio only (THIS DOWNLOAD AT AROUND 30 KB/SEC)

size_bytes = yt.streams.get_by_itag(itag).filesize
print(f'File size: {size_bytes} bytes')

stream = yt.streams.get_by_itag(itag)
print(f'Will start the download:')
time_before = datetime.datetime.utcnow()
stream.download(filename=f'{youtube_episode_id}.mp4', skip_existing=False, max_retries=2)
download_time = datetime.datetime.utcnow() - time_before
print(f'Downloading time: {download_time.total_seconds()} seconds')
print(f'Average speed:    {size_bytes/download_time.total_seconds()/1024} kB/s ')
```

**Comment by Nobody12here** [comment]
Yeah! I'm also facing the same issue when i have applied the patch as explained by @Gabeperson.
The issue may seem to be with the `default_range_size` value. 
EDIT: I have seen that the `stop_pos` variable inside the stream function is only showing the value of `default_range_size`. Hence this is the main issue because its ordering to stop at 9MB instead of the acutal filesize.In short the `filesize` variable does not get updated

**Comment by Gabeperson** [comment]
@sukhoi47 @Nobody12here 
I've tested a fix for the truncation issue, and edited my original post. Could you see if the issue still persists?

**Comment by NannoSilver** [comment]
> @sukhoi47 @Nobody12here I've tested a fix for the truncation issue, and edited my original post. Could you see if the issue still persists?

@Gabeperson 
I did some tests and it performed very well, without the truncation, but I am conducting more tests.
Thank you for your great job!

**Comment by lolzhunter** [comment]
after fixing a little formatting issue and removing the print statement it works great (personal choice, it doesn't cause any functional issue), once it gets the greenlight shouldn't be hard at all to incorporate the change to the main branch

**Comment by Gabeperson** [comment]
> after fixing a little formatting issue and removing the print statement it works great (personal choice, it doesn't cause any functional issue), once it gets the greenlight shouldn't be hard at all to incorporate the change to the main branch

Whoops. I meant to remove that print statement. It was used for debugging, but I must've missed removing it. Thanks for reminding me!

**Comment by Mchoga** [comment]
Thank you @Gabeperson, your solution worked for me

**Comment by md500** [comment]
Getting this error using @sukhoi47 and @Gabeperson soluctions.

>`options for download: [<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="8fps" vcodec="mp4v.20.3" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2" progressive="True" type="video">, <Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028" progressive="False" type="video">, <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="399" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="av01.0.08M.08.0.110.01.01.06.0" progressive="False" type="video">, <Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001f" progressive="False" type="video">, <Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="398" mime_type="video/mp4" res="720p" fps="30fps" vcodec="av01.0.05M.08.0.110.01.01.06.0" progressive="False" type="video">, <Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="397" mime_type="video/mp4" res="480p" fps="30fps" vcodec="av01.0.04M.08.0.110.01.01.06.0" progressive="False" type="video">, <Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="396" mime_type="video/mp4" res="360p" fps="30fps" vcodec="av01.0.01M.08.0.110.01.01.06.0" progressive="False" type="video">, <Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015" progressive="False" type="video">, <Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="395" mime_type="video/mp4" res="240p" fps="30fps" vcodec="av01.0.00M.08.0.110.01.01.06.0" progressive="False" type="video">, <Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c" progressive="False" type="video">, <Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9" progressive="False" type="video">, <Stream: itag="394" mime_type="video/mp4" res="144p" fps="30fps" vcodec="av01.0.00M.08.0.110.01.01.06.0" progressive="False" type="video">, <Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">, <Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus" progressive="False" type="audio">, <Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">]`

```---------------------------
duration: 33320 seconds
Traceback (most recent call last):
  File "C:\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Python311\Lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Python311\Lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\socket.py", line 850, in create_connection
    raise exceptions[0]
  File "C:\Python311\Lib\socket.py", line 835, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
```

During handling of the above exception, another exception occurred:

```

Traceback (most recent call last):
  File "C:\Users\mauri\Documents\downloads.py", line 23, in <module>
    size_bytes = yt.streams.get_by_itag(itag).filesize
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\AppData\Roaming\Python\Python311\site-packages\pytube\streams.py", line 157, in filesize
    self._filesize = request.filesize(self.url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\AppData\Roaming\Python\Python311\site-packages\pytube\request.py", line 205, in filesize
    return int(head(url)["content-length"])
               ^^^^^^^^^
  File "C:\Users\mauri\AppData\Roaming\Python\Python311\site-packages\pytube\request.py", line 270, in head
    response_headers = _execute_request(url, method="HEAD").info()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\AppData\Roaming\Python\Python311\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder>```
```

Only changed itag to 22 and youtube_episode_id to ivdTnPl1ND0 (another video), max_retries=2 to max_retries=10 and fails.
```
If i use only @Gabeperson solution, download begins:

```
```
duration: 33320 seconds
File size: 1182125772 bytes
Will start the download:
 ↳ |██████████████████████████████████████                            | 57.5%
```


But download speed is not constant. it stays at 0mbps (sometimes 6s,30s and 60s) then it downloads at full speed for 2seconds. You can see this on task manager. Weird.

**Comment by NannoSilver** [comment]
@md500 
I just tested itag =22 and youtube_episode_id = ivdTnPl1ND0
Worked fine here.

Is likely you did some mistake in the implementation of the [patch](https://github.com/pytube/pytube/issues/1489#issuecomment-1452868684) developed by @Gabeperson

**Comment by rgryta** [comment]
@Gabeperson, do you maybe have a forked repo together with this fix?
I started maintaining a small fork of pytube, merging others' pull requests with fixes into it. Unless you're okay with me just taking that solution and pushing the update as my own.
(I'm not planning on making this an actual working fork, just "barely" functioning one)

**Comment by Gabeperson** [comment]
> @Gabeperson, do you maybe have a forked repo together with this fix? I started maintaining a small fork of pytube, merging others' pull requests with fixes into it. Unless you're okay with me just taking that solution and pushing the update as my own. (I'm not planning on making this an actual working fork, just "barely" functioning one)

Sure. I've just created a PR on your pytube repo.

**Comment by rgryta** [comment]
Thanks! I usually scroll through PRs from this main repository and manually add their respective remotes to mine so you saved me a bit of time there.

**Comment by jangroth** [comment]
Dump question - I quietly assumed a PR against this repo _and a new release_ are only days away. Looking at the 58 open PRs and the fact that nobody has created something yet make me think I might be wrong?

Is this pytube/pytube still maintained?

**Comment by rgryta** [comment]
No idea.

There have been 11 PR reviews in the last year. Last four were in December. And the last major fix that I remember was in May - throttling function 
thing. I'm using pytube for some obscure personal project and have used some of the submitted PRs for my own fork to keep it away from crashing.

In my opinion though, this project seems to need more maintainers.

**Comment by RONNCC** [comment]
@rgryta  :-) if you want to submit PRs to main, happy to review  (just tag me there)

**Comment by rgryta** [comment]
> 

> @rgryta :-) if you want to submit PRs to main, happy to review (just tag me there)

I will remember that :). There are 2 that I submitted quite some time ago so I'll leave them be as they are.
Good to see someone updating this project (got several notification emails today already, lol).

**Comment by opc241** [comment]
Even after this fix from @Gabeperson, the download speed is still very slow on my side.

**Comment by NannoSilver** [comment]
> Even after this fix from @Gabeperson, the download speed is still very slow on my side.

This fix is outdated. There are new problems after that.
Fix is here:
https://github.com/pytube/pytube/pull/1575/files

**Comment by Gabeperson** [comment]
@opc241 @sukhoi47 I've updated the original comment to reflect that the temporary fix should not be used anymore. Thanks for the notification.

**Comment by RONNCC** [comment]
From my understanding the issues / fixes here should be fixed and merged to main (thanks to the contributors there)

**Comment by opc241** [comment]
Thanks for the hint and the link ... maybe i'm doing wrong, but i am still facing a slow download speed at about 20 kbit/s. I included the fix from https://github.com/pytube/pytube/pull/1575/files
Should i change the client to 'WEB' again? Here it was set to 'ANDROID_MUSIC'?

**Comment by RONNCC** [comment]
@opc241  could you try both of them out and see which works better -- we can patch it back to WEB perhaps if that is better
