### ISSUE TITLE
404 Error for some videos

### ISSUE THREAD

**Issue by cdowen** [pytube/pytube#405]
404 Error for video https://www.youtube.com/watch?v=KMtgexdtcGY.
The url is fine in a browser.
Bug report attached below.

[yt-video-KMtgexdtcGY-1560972844.json.gz](https://github.com/nficano/pytube/files/3308657/yt-video-KMtgexdtcGY-1560972844.json.gz)

**Comment by stdedos** [comment]
It seems your issue is solved on the newest version. Download the newest version with `pip install git+https://github.com/nficano/pytube.git --upgrade` and try again

**Comment by elDudarino** [comment]
I am having the same issues still with the latest commit pointed out by @stdedos 

Anyone have any other ideas?
