### ISSUE TITLE
KeyError: 'streamingData'

### ISSUE THREAD

**Issue by Iftakharpy** [pytube/pytube#743]
### I was trying to download https://www.youtube.com/watch?v=NdA778dQrXE

And this always raises KeyError: 'streamingData' error.

```python3
>>> YouTube("https://www.youtube.com/watch?v=NdA778dQrXE")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\extract.py", line 281, in apply_descrambler
    formats = json.loads(stream_data["player_response"])["streamingData"]["formats"]
KeyError: 'streamingData'
```

List of some videos raises the same error.
- https://www.youtube.com/watch?v=ltneTZ9uRGw
- https://www.youtube.com/watch?v=fp3vOzVQL5c

**Comment by ghost** [comment]
It is working for me. Can you try it once again? If the problem persists, reinstall pytube from the repository. I am using the repository version.

**Comment by Iftakharpy** [comment]
I am using:
Python             3.8.5
pytube             9.6.0
pytube3           9.6.4

still having the same problem.

**Comment by ghost** [comment]
> I am using:
> Python 3.8.5
> pytube 9.6.0
> pytube3 9.6.4
> 
> still having the same problem.

Yeah, I also got an error when I tried it again. Sometimes it works, sometimes it doesn't. Its a pytube problem.

**Comment by yehya-dev** [comment]
I am having the same issue! Not with all videos but some videos.

**Comment by andipahlevy** [comment]
i am having the same issue

**Comment by tfdahlin** [comment]
If you install both pytube3 and pytube with pip, certain files get overwritten in unintended ways. This is especially true because the pypi packages haven't been updated in several months.

You should be able to fix this problem if you do the following:
1. Run `pip uninstall pytube`
2. Run `pip uninstall pytube3`
3. Run `python -m pip install git+https://github.com/nficano/pytube`

This should uninstall the conflicting versions of pytube, and install the most recent code from this repository.

**Comment by raghav330** [comment]
Now getting the error below:
`Traceback (most recent call last):
  File "/Users/raghavgurung/PycharmProjects/yt_download/get_youtube_videos.py", line 3, in <module>
    yt = YouTube("https://www.youtube.com/watch?v=hC8CH0Z3L54")
  File "/Users/raghavgurung/PycharmProjects/yt_download/.venv/lib/python3.9/site-packages/pytube/__main__.py", line 103, in __init__
    self.descramble()
  File "/Users/raghavgurung/PycharmProjects/yt_download/.venv/lib/python3.9/site-packages/pytube/__main__.py", line 147, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/Users/raghavgurung/PycharmProjects/yt_download/.venv/lib/python3.9/site-packages/pytube/extract.py", line 281, in apply_descrambler
    formats = json.loads(stream_data["player_response"])["streamingData"][
KeyError: 'formats'
`

**Comment by raghav330** [comment]
I uninstalled everything in my virtualenv and installed through
`python -m pip install git+https://github.com/nficano/pytube`
Getting the below error now:
```
Traceback (most recent call last):
  File "/Users/raghavgurung/PycharmProjects/yt_download/get_youtube_videos.py", line 3, in <module>
    yt = YouTube("https://www.youtube.com/watch?v=hC8CH0Z3L54")
  File "/Users/raghavgurung/PycharmProjects/yt_download/.venv/lib/python3.9/site-packages/pytube/__main__.py", line 103, in __init__
    self.descramble()
  File "/Users/raghavgurung/PycharmProjects/yt_download/.venv/lib/python3.9/site-packages/pytube/__main__.py", line 147, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/Users/raghavgurung/PycharmProjects/yt_download/.venv/lib/python3.9/site-packages/pytube/extract.py", line 281, in apply_descrambler
    formats = json.loads(stream_data["player_response"])["streamingData"][
KeyError: 'formats'
```

**Comment by tfdahlin** [comment]
@raghav330 I'm not getting that problem myself, but I'll look into it. It's possible that the issue extends beyond just what I fixed, and I'm running into some unexpected problems with some unit tests I'm writing, so I'll investigate some more.

**Comment by tfdahlin** [comment]
This should be resolved in https://github.com/nficano/pytube/pull/775, so I'm closing the issue.

@raghav330 I believe I fixed your problem with https://github.com/nficano/pytube/pull/790

**Comment by thisismygitrepo** [comment]
Shouldn't close it that fast. March 2022, and the problem is still there.
version 12

**Comment by thisismygitrepo** [comment]
Apparently the view I'm trying to download is age restricted

https://www.youtube.com/watch?v=v4HkASndEXo

The error is not intuitive.

**Comment by sayyid5416** [comment]
> Apparently the view I'm trying to download is age restricted
> 
> https://www.youtube.com/watch?v=v4HkASndEXo
> 
> The error is not intuitive.

Yes, I got the same error

Also on this video: http://www.youtube.com/watch?v=PVePPxUZivk

**Comment by scottfleming** [comment]
Same issue here, error appears to occur with age restricted videos...

**Comment by fnicolaim** [comment]
Hello, same issue with this video which is also age restricted: https://www.youtube.com/watch?v=sBzrzS1Ag_g

Also tried using pytube over the link adding the has_verified=1 variable but it does not work neither.

**Comment by MaxWolf-01** [comment]
@tfdahlin I think this Issue should be opened again, since as @ thisismygitrepo points out, the error is unintuitive and I think caused by the `check_availability` method not raising `AgeRestrictedError` when a login is required, but the only reason being checked for is if the video is private, not age restricted, as shown in the debugging screenshot.
(url used: https://www.youtube.com/watch?v=EbeLCo5pGiI, pytube 12.1.0)
```
  _ = YT.streams
File "C:\Users\..\pytube\__main__.py", line 296, in streams
  return StreamQuery(self.fmt_streams)
File "C:\Users\...\pytube\__main__.py", line 176, in fmt_streams
  stream_manifest = extract.apply_descrambler(self.streaming_data)
File "C:\Users\...\pytube\__main__.py", line 161, in streaming_data
  return self.vid_info['streamingData']
KeyError: 'streamingData'
```
![debug_pytube_keyerror](https://user-images.githubusercontent.com/69987866/187282984-48b3c108-9b2e-486e-afb1-b7279d89aae2.png)

**Comment by githubfoam** [comment]
@MaxWolf-01  Even you raise "AgeRestrictedError" exception it does not matter; seems like pytube does not allow you to download  log-in requiring videos; did not see where pythube lets you log in youtube in the code btw ; if pytube lets you log in youtube I think it will work; in debug mode you can see all the variables.

>                     raise exceptions.VideoUnavailable(video_id=self.video_id)
            elif status == 'LOGIN_REQUIRED':
                if reason == 'Sign in to confirm your age':
                    print("Sign in to confirm your age required")
                # if reason == (
                #     'This is a private video. '
                #     'Please sign in to verify that you may see it.'
                # ):
                #     raise exceptions.VideoPrivate(video_id=self.video_id)
                    raise exceptions.AgeRestrictedError(video_id=self.video_id)
                else:
                    raise exceptions.VideoUnavailable(video_id=self.video_id)
            elif status == 'ERROR':
                if reason == 'Video unavailable':

**Comment by MaxWolf-01** [comment]
@githubfoam You can set `oauth=True` and connect to your YouTube account. Is that fundamentally different from logging in?

**Comment by githubfoam** [comment]
@MaxWolf-01 did you try  logging in youtube and with "AgeRestrictedError" exception ?

**Comment by MaxWolf-01** [comment]
@githubfoam I don't have a YouTube account that would allow AgeRestricted videos, regardless, I would expect to get an AgeRestrictedError and not KeyError?

**Comment by uvery9** [comment]
i have the same issue:

!  Traceback (most recent call last):
  File "YoutubeDownloader.py", line 444, in <module>
  File "YoutubeDownloader.py", line 349, in main
  File "pytube\__main__.py", line 296, in streams
  File "pytube\__main__.py", line 176, in fmt_streams
  File "pytube\__main__.py", line 161, in streaming_data
KeyError: 'streamingData'

Try to download video from:  https://www.youtube.com/watch?v=eB-ueibm8Kw

**Comment by githubfoam** [comment]
> @githubfoam I don't have a YouTube account that would allow AgeRestricted videos, regardless, I would expect to get an AgeRestrictedError and not KeyError?
I do not think it is about "AgeRestrictedError " I added exceptions, the previous code piece is what I tested in debug mode; Agerestricted video configuration is not about youtube account but youtube video; I could not find agerestricted youtube video btw.

**Comment by sedwardsmarsh** [comment]
This is still an issue for me. I get this error on the following video: [https://www.youtube.com/watch?v=-N_vl1d7TFA&t=30s](https://www.youtube.com/watch?v=-N_vl1d7TFA&t=30s), which seems to be a really dead link.

My solution was to call `pytube.YouTube(video_url)` and look at the channel_id. For the weird link I provided, this is None.

```python3
from pytube import YouTube, exceptions

# attempt to download the video
try:
    yt = YouTube(video_url)

    # check the object to see if it hasn't loaded properly
    if yt.channel_id == None:
        # do something
        ...

except exceptions.VideoUnavailable:
    ...

else:
    ...
```

**Comment by GrahamboJangles** [comment]
Having this issue with age-restricted videos.

**Comment by iyotee** [comment]
same with age-restricted

**Comment by MICROWAVE-web** [comment]
![image](https://user-images.githubusercontent.com/74858759/209910150-5706f784-004f-47ce-9931-07ee24d8903a.png)

**Comment by clivet268** [comment]
Same issue with age restricted videos

**Comment by murillo2030** [comment]
This error is in pytube.__main__.check_availability function, that correct detect the status "LOGIN_REQUIRED" but the reason variable is the problem, just because in line 223 of __main__.py it try compare a string with a tuple where have another strings, a dude say it's because pytube don't release anymore in pip package and so is outdate. Solution can be remove reason if statments or add to tuple and modify == statment by "in" because don't have any logical reasons to compare a str with tuple.


![tmp_1](https://user-images.githubusercontent.com/100052495/226718299-2aa05dd2-cee4-4c43-9a09-8f9886c2f951.png)

Here's the person I mentioned:

![tmp_2](https://user-images.githubusercontent.com/100052495/226719868-7915aa2a-9a87-4033-9250-d6b7a616e1e7.png)

**Comment by TyreseJ-246** [comment]
The error happens to me because the video is not public to non login users , because some videos have some restrictions and need to be log in to access the video , pytube dont log in so he cannot download this type of videos. I found this printing the reason variable on the code that [MurilloMB] gave. The solution is to go find other equal video on youtube, or on other place, or download with other tool that uses login.

**Comment by omkarpyc** [comment]
I finally got a solution for this KeyError: 'Streaming Data'.
This error arises if you are trying to download videos that require a sign in / login for example Age Restricted videos require sign in or login. I tried to keep an exception for Age Restricted from pytube.exceptions but the error still persists because the statement for exception didn't actually run for some reason. Actually this is not even an error but a bug.

Solution
I included several exception in below example i am trying to download the Youtube 8m dataset.


        for video_id in video_id_list:
            try:
                YouTube('http://youtube.com/watch?v=' + video_id).streams.get_highest_resolution().download(vedio_dir)
            except (VideoUnavailable, HTTPError, ConnectionError,RemoteDisconnected, ConnectTimeout, InvalidURL, ProtocolError, AgeRestrictedError, VideoRegionBlocked, LiveStreamError, RecordingUnavailable, MembersOnly, VideoPrivate, Exception):
                try:
                    YouTube('http://youtube.com/watch?v=' + video_id).streams.get_highest_resolution().download(vedio_dir)
                except (VideoUnavailable, HTTPError, ConnectionError,RemoteDisconnected, ConnectTimeout, InvalidURL, ProtocolError, AgeRestrictedError, VideoRegionBlocked, LiveStreamError, RecordingUnavailable, MembersOnly, VideoPrivate, Exception):
                    print(' http://youtube.com/watch?v=' + video_id)



This made me download those videos without problem.
Kindly try even if my solution looks silly.

**Comment by Bipul-Chandra-Mondol** [comment]
File "c:\Users\asus\OneDrive\Desktop\demo\tube.py", line 3, in <module>
    yt.streams
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams       
    return StreamQuery(self.fmt_streams)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams   
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
I can't solve this problem please help

**Comment by q4udebobrota** [comment]
I am also getting the same issue.

Traceback (most recent call last):
  File "D:\pythonProjects\youtube-downloader\youtube-downloader-converter-master\code.py", line 35, in <module>
    stream = str(yt.streams.filter(progressive=True))
  File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'


please help me with a solution

**Comment by TomsBicans** [comment]
I am having an exact problem like the others. I was using to download youtube playlists, but the exception was being raised on each video. This is one of the videos: https://www.youtube.com/watch?v=2SLb8f3NA5w

  File "C:\Users\feagl\Documents\GIT_REPOS\twitch-spy\py3.10\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\feagl\Documents\GIT_REPOS\twitch-spy\py3.10\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\feagl\Documents\GIT_REPOS\twitch-spy\py3.10\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

**Comment by Tarufetti** [comment]
Seems that something happened over the last month or so, because I coded my program, made it into EXE and everything run smoothly up until yesterday. Using Oauth set to True when calling the Youtube(url) object seems to fix the error, but it is a bummer to ask my program's users to log in to YT before being able to download anything,

**Comment by dxbstyle** [comment]
Can confirm, getting the same error

**Comment by trantrungpixta** [comment]
Sometimes it works, sometimes it does not work. Please help.

**Comment by chrisblackwood35** [comment]
I´m having the same issue. Any thoughts?

**Comment by DuranTonee** [comment]
> I´m having the same issue. Any thoughts?

Apparently, everyone started getting that error. Me as well, I just switched to yt-dlp (https://github.com/yt-dlp/yt-dlp) and it works perfectly now

**Comment by stevannetto** [comment]
Same error here.
Linux Mint 21.1
Python 3.10.6
pytube-12.1.3

>>> from pytube import YouTube
>>> yt = YouTube("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
>>> streams = yt.streams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tevo/.local/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/tevo/.local/lib/python3.10/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/tevo/.local/lib/python3.10/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
>>>

**Comment by debdip** [comment]
Having same issue.
![image](https://user-images.githubusercontent.com/11462610/235114397-b71bdf0e-4442-4893-b88e-8e2b63a27bf7.png)

**Comment by ghost** [comment]
Got the same issue

**Comment by acerock6** [comment]
Same issue as well. Is there a fix already ?

**Comment by ViniciusOSAntos** [comment]
![image](https://user-images.githubusercontent.com/43036615/235195961-9cd3517f-e59b-422a-9e71-9ac0534e5b3f.png)
Same issue

**Comment by andrii1** [comment]
Same issue...

**Comment by wudstrand** [comment]
Same issue...

**Comment by andrii1** [comment]
For me, it worked recently with few additional attempts, but now I switched to yt-dlpOn Apr 28, 2023, at 8:54 PM, Will Udstrand ***@***.***> wrote:﻿
Same issue...

**Comment by andresvanegas19** [comment]
I tried switching to other libraries but none of them worked. Did anyone find an answer?

**Comment by sumanthrao-maraboina** [comment]
**First locate pytube library location** 

![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)

**Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**

![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)

It worked pretty well for me but the problem is downloading video or audio is slow

**Comment by Thxssio** [comment]
I solved the problem in linux as follows:
```
sudo gedit  /usr/local/lib/python3.8/dist-packages/pytube/innertube.py

```
Wait...

Change the line:

```
class InnerTube:
    """Object for interacting with the innertube API."""
    def __init__(self, client='ANDROID', use_oauth=False, allow_cache=True):
        """Initialize an InnerTube object.

        :param str client:
            Client to use for the object.
            Default to web because it returns the most playback types.
        :param bool use_oauth:
            Whether or not to authenticate to YouTube.
        :param bool allow_cache:
            Allows caching of oauth tokens on the machine.
        """
        self.context = _default_clients[client]['context']
        self.api_key = _default_clients[client]['api_key']
        self.access_token = None
        self.refresh_token = None
        self.use_oauth = use_oauth
        self.allow_cache = allow_cache

```
for
 
```
class InnerTube:
    """Object for interacting with the innertube API."""
    def __init__(self, client='WEB', use_oauth=False, allow_cache=True):
        """Initialize an InnerTube object.

        :param str client:
            Client to use for the object.
            Default to web because it returns the most playback types.
        :param bool use_oauth:
            Whether or not to authenticate to YouTube.
        :param bool allow_cache:
            Allows caching of oauth tokens on the machine.
        """
        self.context = _default_clients[client]['context']
        self.api_key = _default_clients[client]['api_key']
        self.access_token = None
        self.refresh_token = None
        self.use_oauth = use_oauth
        self.allow_cache = allow_cache

```
`line 78`
Only change the client from Android to WEB, probably the problem only occurs for android due to an update.

**Comment by barleyj21** [comment]
Same issue here. There's a way to make it work, but much slower: https://github.com/pytube/pytube/issues/743#issuecomment-1528453973  (I tried  it and it's working)

**Comment by benqbed** [comment]
Bumping this issue as I'm having it too. Not even with age restricted videos only, I get it for every video I try. I'm currently not sure if I can implement the fix in https://github.com/pytube/pytube/issues/743#issuecomment-1528453973 as I'm running my bot on heroku, will look into options. I'm not sure if there's a priority system for bugs, but this seems like it should shoot up to the top in importance.

Edit: might open new issue referencing this one
Edit2: nvm seems like plenty of people already have, guess we just gotta implement fix on our own/wait for fix to be pushed to main

**Comment by ghost** [comment]
You can solve the problem by changing to client from ANDROID to WEB as mentionned before but the download speed is so low...
Any fix about that ?

**Comment by Bipul-Chandra-Mondol** [comment]
still now i can't solve this problem

**Comment by shelbygreen** [comment]
having the same issue

**Comment by Flexonze** [comment]
Same issue here. This was happening randomly before, but it's been occuring much more in the last couple days.

**Comment by pratikCMEX** [comment]
same issue.

**Comment by pratikCMEX** [comment]
it's taking so much loading when I change 
client='ANDROID' 
To
client='WEB'

**Comment by pratikCMEX** [comment]
Exception: HTTP Error 403: Forbidden

**Comment by samuelbraun04** [comment]
> Exception: HTTP Error 403: Forbidden

Getting the same error when I change from ANDROID to WEB

**Comment by manni-live** [comment]
> **First locate pytube library location**
> 
> ![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)
> 
> **Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**
> 
> ![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)
> 
> It worked pretty well for me but the problem is downloading video or audio is slow

Thanks for this. This fixed the issue! by changing the innertube.py from ANDROID to WEB it seems to go much slower. Is their any fix for that?

Thanks a ton!

**Comment by AldenirLuiz** [comment]
Hello everyone,

I would like to inform you that I made some changes to the code to visualize the data in the response. As a result, the output includes an error message that points to the player version used.

The specific error message is as follows:

'playerErrorMessageRenderer': {'subreason': {'runs': [{'text': 'Watch on the latest version of YouTube.', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwig0Ky409b-AhWSC5EKHaDNDSE=', 'urlEndpoint': {'url': 'market://details?id=com.google.android.youtube&url=https%3A%2F%Fwww.youtube.com%2Fwatch%3Fv%3DrIcf_cToq5c', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'learnMore': {'runs': [{'text': 'Learn more', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwig0Ky409b-AhWSC5EKHaDNDSE=', 'urlEndpoint': {'url': '//support.google.com/youtube/answer/12318250?hl=en', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'reason': {'runs': [{'text': 'The following content is not available on this app.'}]}, 'thumbnail': {'thumbnails': [{'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}, {'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}]}}

This error message indicates that the content is not available on the app because it requires the latest version of YouTube to be played. Therefore, updating the player version may be necessary to resolve this issue. 

I also added a line of code in `bypass_age_gate()` on line 269 in `__main__.py` to print the error screen:

```python
print(innertube_response['playabilityStatus'].get('errorScreen'))
```

Please let me know if you have any questions or suggestions. Thank you!

**Comment by Rahulsharma4298** [comment]
why is this closed? It is still not working

**Comment by powerlock** [comment]
It is still the same issue now with the following video, not age restricted. "https://www.youtube.com/watch?v=iJCV_2H9xD0"

Here are the details of the all attributes.
Seems the object was not retrieved correctly. We should add an error to notice whether it is rejected by youtube or other issues.

_age_restricted = None
_author = None
_embed_html = None
_fmt_streams = None
_initial_data = None
_js = None
_js_url = None
_metadata = None
_player_config_args = None
_publish_date = None
_title = None
_vid_info = {'responseContext': {'visitorData': 'CgsxWVV0SVhPbG9FUSiil8WiBg%3D%3D', 'serviceTrackingParams': [{'service': 'GFEEDBACK', 'params': [{'key': 'ipcc', 'value': '0'}, {'key': 'is_alc_surface', 'value': 'false'}, {'key': 'is_viewed_live', 'value': 'False'}, {'key': 'logged_in', 'value': '0'}, {'key': 'e', 'value': '9405958,23880830,23880833,23880836,23888716,23918597,23946420,23966208,23983296,23998056,24004644,24007246,24034168,24036947,24077241,24080738,24117491,24120820,24135310,24135942,24140247,24160765,24160767,24160769,24160771,24181174,24187043,24187377,24211178,24219382,24219713,24236210,24241378,24255165,24255543,24255545,24255547,24255549,24262346,24265964,24285788,24288664,24289856,24290971,24296354,24390675,24404640,24406318,24407191,24407198,24409417,24414719,24421916,24421920,24429094,24439483,24440132,24440407,24442764,24442766,24443595,24451319,24453870,24453872,24455284,24455285,24455286,24457383,24457385,24457387,24458317,24458324,24458329,24458839,24459436,24463873,24465011,24465641,24465643,24466371,24467897,24468691,24468724,24471752,24483503,24485239,24485421,24486580,24487766,24488188,24489886,24494077,24494984,24495060,24495838,24495960,24495971,24495984,24498024,24498300,24499291,24499306,24499570,24499575,24510060,24510545,24511627,24511629,24512742,24513409,24515366,24515424,24516017,24518452,24519102,24519143,24530357,24531244,24532513,24532854,24537200,24537812,24550812,24550814,24550816,24552125,24552156,24552164,24552606,24553414,24554806,24555242,24555688,24556101,24556890,24556892,24557847,24557856,24690497,39323074,39323605,39323606'}]}, {'service': 'CSI', 'params': [{'key': 'c', 'value': 'ANDROID'}, {'key': 'cver', 'value': '16.20'}, {'key': 'yt_li', 'value': '0'}, {'key': 'GetPlayer_rid', 'value': '0x55bbb59886b2bceb'}]}, {'service': 'GUIDED_HELP', 'params': [{'key': 'logged_in', 'value': '0'}]}, {'service': 'ECATCHER', 'params': [{'key': 'client.version', 'value': '16.20'}, {'key': 'client.name', 'value': 'ANDROID'}, {'key': 'client.fexp', 'value': '24555242,24219382,24429094,24550812,24467897,24494077,24034168,24471752,24552164,24219713,24468724,24555688,24499570,24512742,24404640,24515366,24495960,24488188,24498024,24495838,24510060,24080738,24135310,24453870,24495060,23966208,24513409,24552156,24255547,24181174,24160771,24489886,24443595,24532513,23918597,24457387,24288664,24236210,24453872,24160765,24557847,24519143,24451319,24550814,24531244,24537812,24285788,24537200,24556890,24255543,23946420,24421916,24499575,23880833,24439483,24511627,24515424,24390675,24487766,24518452,23888716,24466371,24485421,24255549,24135942,24187043,24211178,24486580,24160767,23998056,24557856,24289856,24036947,23983296,24187377,24457383,24516017,24458324,24550816,24510545,24465011,24556101,24556892,24552125,24458317,24495971,24440132,24442764,24455284,24554806,24406318,24495984,24421920,24007246,24296354,24262346,24483503,24690497,24552606,24499306,24290971,24465643,24498300,24120820,24265964,24409417,24140247,24407191,24458329,24455285,24485239,24499291,24457385,23880836,24117491,24255165,39323605,24553414,24494984,24414719,24463873,24407198,24511629,24532854,24530357,24241378,23880830,39323074,24440407,24255545,24455286,39323606,24468691,24004644,9405958,24458839,24465641,24077241,24459436,24160769,24519102,24442766'}]}, {'service': 'LISTNR', 'params': [{'key': 'e', 'value': '24459436,24135942,24466371,24458839,24519102,24518452,39323606,24410415,24490319,24515424,24511627,24439483,39323074,24253767,24556890,24537200,24519143,24451319,39323605,24255165,24117491,24024517,24458329,24288664,24407191,24485239,24140247,24409417,24254870,24290971,24250570,24181174,24552606,24498300,24532513,24483503,24262346,24220751,24440132,24455284,24495060,24406318,24495838,24556101,24135310,24286257,24404640,24030282,24516017,24033252,24465011,24458324,24488188,24515366,24253780,24510545,24458317,24034168,24457383,24036947,24555242,24253784,24274141,24550812'}]}, {'service': 'SUGGEST', 'params': [{'key': 'sugexp', 'value': 'uqapahn21,ytpso.bo.me=0,ytpsoso.bo.me=0,ytpso.bo.bro.mi=24474129,ytpsoso.bo.bro.mi=24474129,cfro=1,ytpso.bo.me=1,ytpsoso.bo.me=1,ytpso.bo.bro.mi=24457588,ytpsoso.bo.bro.mi=24457588'}]}]}, 'playabilityStatus': {'status': 'ERROR', 'reason': 'This video is unavailable', 'errorScreen': {'playerErrorMessageRenderer': {'subreason': {'runs': [{'text': 'Watch on the latest version of YouTube.', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwi3u_XCl9f-AhUn0ZQJHb6ZA44=', 'urlEndpoint': {'url': 'market://details?id=com.google.android.youtube&url=https%3A%2F%Fwww.youtube.com%2Fwatch%3Fv%3DiJCV_2H9xD0', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'learnMore': {'runs': [{'text': 'Learn more', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwi3u_XCl9f-AhUn0ZQJHb6ZA44=', 'urlEndpoint': {'url': '//support.google.com/youtube/answer/12318250?hl=en', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'reason': {'runs': [{'text': 'The following content is not available on this app.'}]}, 'thumbnail': {'thumbnails': [{'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}, {'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}]}}}, 'skip': {'playabilityErrorSkipConfig': {'skipOnPlayabilityError': False}}, 'contextParams': 'Q0FFU0FnZ0I='}, 'trackingParams': 'CAAQu2kiEwi3u_XCl9f-AhUn0ZQJHb6ZA44=', 'playerSettingsMenuData': {'loggingDirectives': {'trackingParams': 'CAEQtc4GIhMIt7v1wpfX_gIVJ9GUCR2-mQOO', 'visibility': {'types': '12'}, 'enableDisplayloggerExperiment': True}}}
_watch_html = None
age_restricted = False
allow_oauth_cache = True
author = unknown
bypass_age_gate = <bound method YouTube.bypass_age_gate of <pytube.__main__.YouTube object: videoId=iJCV_2H9xD0>>
caption_tracks = []
captions = {}
channel_id = None
channel_url = https://www.youtube.com/channel/None
check_availability = <bound method YouTube.check_availability of <pytube.__main__.YouTube object: videoId=iJCV_2H9xD0>>
description = None
embed_html = <!DOCTYPE html><html lang="en" dir="ltr" data-cast-api-enabled="true"><head><meta name="viewport" content="width=device-width, initial-scale=1"><style name="www-roboto" nonce="ULDCvV2qKRV1xcZcvmJ7Jg">@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxP.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:500;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc9.ttf)format('truetype');}</style><script name="www-roboto" nonce="SqG4aeFy8zgQQ8ieIQCqXw">if (document.fonts && document.fonts.load) {document.fonts.load("400 10pt Roboto", "E"); document.fonts.load("500 10pt Roboto", "E");}</script><link rel="stylesheet" href="/s/player/0c487f05/www-player.css" name="www-player" nonce="ULDCvV2qKRV1xcZcvmJ7Jg"><style nonce="ULDCvV2qKRV1xcZcvmJ7Jg">html {overflow: hidden;}body {font: 12px Roboto, Arial, sans-serif; background-color: #000; color: #fff; height: 100%; width: 100%; overflow: hidden; position: absolute; margin: 0; padding: 0;}#player {width: 100%; height: 100%;}h1 {text-align: center; color: #fff;}h3 {margin-top: 6px; margin-bottom: 3px;}.player-unavailable {position: absolute; top: 0; left: 0; right: 0; bottom: 0; padding: 25px; font-size: 13px; background: url(/img/meh7.png) 50% 65% no-repeat;}.player-unavailable .message {text-align: left; margin: 0 -5px 15px; padding: 0 5px 14px; border-bottom: 1px solid #888; font-size: 19px; font-weight: normal;}.player-unavailable a {color: #167ac6; text-decoration: none;}</style><script nonce="SqG4aeFy8zgQQ8ieIQCqXw">var ytcsi={gt:function(n){n=(n||"")+"data_";return ytcsi[n]||(ytcsi[n]={tick:{},info:{}})},now:window.performance&&window.performance.timing&&window.performance.now&&window.performance.timing.navigationStart?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()},tick:function(l,t,n){var ticks=ytcsi.gt(n).tick;var v=t||ytcsi.now();if(ticks[l]){ticks["_"+l]=ticks["_"+l]||[ticks[l]];ticks["_"+l].push(v)}ticks[l]=v},info:function(k,
v,n){ytcsi.gt(n).info[k]=v},setStart:function(t,n){ytcsi.tick("_start",t,n)}};
(function(w,d){ytcsi.setStart(w.performance?w.performance.timing.responseStart:null);var isPrerender=(d.visibilityState||d.webkitVisibilityState)=="prerender";var vName=!d.visibilityState&&d.webkitVisibilityState?"webkitvisibilitychange":"visibilitychange";if(isPrerender){var startTick=function(){ytcsi.setStart();d.removeEventListener(vName,startTick)};d.addEventListener(vName,startTick,false)}if(d.addEventListener)d.addEventListener(vName,function(){ytcsi.tick("vc")},false);function isGecko(){if(!w.navigator)return false;
try{if(w.navigator.userAgentData&&w.navigator.userAgentData.brands&&w.navigator.userAgentData.brands.length){var brands=w.navigator.userAgentData.brands;for(var i=0;i<brands.length;i++)if(brands[i]&&brands[i].brand==="Firefox")return true;return false}}catch(e){setTimeout(function(){throw e;})}if(!w.navigator.userAgent)return false;var ua=w.navigator.userAgent;return ua.indexOf("Gecko")>0&&ua.toLowerCase().indexOf("webkit")<0&&ua.indexOf("Edge")<0&&ua.indexOf("Trident")<0&&ua.indexOf("MSIE")<0}if(isGecko()){var isHidden=
(d.visibilityState||d.webkitVisibilityState)=="hidden";if(isHidden)ytcsi.tick("vc")}var slt=function(el,t){setTimeout(function(){var n=ytcsi.now();el.loadTime=n;if(el.slt)el.slt()},t)};w.__ytRIL=function(el){if(!el.getAttribute("data-thumb"))if(w.requestAnimationFrame)w.requestAnimationFrame(function(){slt(el,0)});else slt(el,16)}})(window,document);
</script><script nonce="SqG4aeFy8zgQQ8ieIQCqXw">var ytcfg={d:function(){return window.yt&&yt.config_||ytcfg.data_||(ytcfg.data_={})},get:function(k,o){return k in ytcfg.d()?ytcfg.d()[k]:o},set:function(){var a=arguments;if(a.length>1)ytcfg.d()[a[0]]=a[1];else for(var k in a[0])ytcfg.d()[k]=a[0][k]}};

**Comment by anabild** [comment]
Hello, 
Recently I got into the same issue.  Solved it by setting the variable transform_plan_raw in  cipher.py  to js. 
So go to {home}/.local/lib/{your_pythonversion: ex. python3.10}/site-packages/pytube/cipher.py Line 411 and replace the value of thetransform_plan_raw variable as follows:

transform_plan_raw = js #find_object_from_startpoint(raw_code, match.span()[1] - 1)

**Comment by Rams901** [comment]
> 

Tried this in google colab. It doesn't work even after runtime restart. Curious why did you try this?

**Comment by Rams901** [comment]
> Hello, Recently I got into the same issue. Solved it by setting the variable transform_plan_raw in cipher.py to js. So go to {home}/.local/lib/{your_pythonversion: ex. python3.10}/site-packages/pytube/cipher.py Line 411 and replace the value of thetransform_plan_raw variable as follows:
> 
> transform_plan_raw = js #find_object_from_startpoint(raw_code, match.span()[1] - 1)

Tried this in google colab. It doesn't work even after runtime restart. Curious why did you try this? @anabild

**Comment by anabild** [comment]
> > Hello, Recently I got into the same issue. Solved it by setting the variable transform_plan_raw in cipher.py to js. So go to {home}/.local/lib/{your_pythonversion: ex. python3.10}/site-packages/pytube/cipher.py Line 411 and replace the value of thetransform_plan_raw variable as follows:
> > transform_plan_raw = js #find_object_from_startpoint(raw_code, match.span()[1] - 1)
> 
> Tried this in google colab. It doesn't work even after runtime restart. Curious why did you try this? @anabild

Hello, 

Got it from https://github.com/pytube/pytube/commit/d6623d8ce39c777f22a5638307c9fceedc01b047 
I am using a virtual env and a VM with Linux and it just worked for me :)

**Comment by 21564669** [comment]
https://github.com/pytube/pytube/issues/743#issuecomment-1528535169 
is working for me on windows pytube v 12.1.3

**Comment by DrewZhu-lab** [comment]
Same issue here : 
windows 11 
pytube 12.1.3 
python 3.10

**Comment by Rams901** [comment]
I had to use both of these propositions in order to work:
1 - change line 78, path_to_lib/pytube/innertube.py 'ANDROID' to 'WEB' [Reference](https://github.com/pytube/pytube/issues/743#issuecomment-1528535169)
2 - use oauth [Reference](https://github.com/pytube/pytube/issues/1594#issuecomment-1533057155)

**Comment by MaoMao0350** [comment]
My situation is using pytube 12.1.3, and downloading a public vedio got such error, the root cause is playability_status method return an array with **1** element in it: None, so we need to change the lib line 213, adding the condition of None:
```
   def check_availability(self):
        """Check whether the video is available.

        Raises different exceptions based on why the video is unavailable,
        otherwise does nothing.
        """
        status, messages = extract.playability_status(self.watch_html)

        for reason in messages:
            if status is None:
                pass
```

**Comment by elulcao** [comment]
The package was working fine, but suddenly stopped working.

```
$ python download_youtube.py
Traceback (most recent call last):
  File "/home/kali/download_youtube.py", line 7, in <module>
    stream = yt.streams.get_highest_resolution()
             ^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 161, in streaming_data

    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'
```

**Comment by tuankietcoderr** [comment]
> 3\. python -m pip install git+https://github.com/nficano/pytube

This works for me! Thank you very much!

**Comment by x0093030** [comment]
> If you install both pytube3 and pytube with pip, certain files get overwritten in unintended ways. This is especially true because the pypi packages haven't been updated in several months.
> 
> You should be able to fix this problem if you do the following:
> 
> 1. Run `pip uninstall pytube`
> 2. Run `pip uninstall pytube3`
> 3. Run `python -m pip install git+https://github.com/nficano/pytube`
> 
> This should uninstall the conflicting versions of pytube, and install the most recent code from this repository.

that worked for me, thank you :)
