### ISSUE TITLE
[BUG] Can't download one specific video

### ISSUE THREAD

**Issue by nanobloom** [pytube/pytube#967]
Downloaded hundreds of videos already, can't download one specific video:
https://www.youtube.com/watch?v=goToXTC96Co
Downloading the playlist was interrupted when it encountered that video. Tried downloading it as video instead, same result - stops right away after downloading 2 MB.
Don't really have any output, errors or exceptions, it's just frozen.
Tried multiple pytube versions (some early versions, as well as 10.5.1 and latest 10.6.1) and neither of them works.
Tried a couple Python versions between 3.6 and latest 3.9.2, neither of them seems to work.
Version of the video that can't be downloaded has itag=22, downloading lower quality video (itag=18) is successful.
Can't 100% tell whether that's a problem with pytube or the video file itself but I thought it might be worth sharing here anyway as I'm also curious what could be the reason.
Also had similar problem with downloading another video but upgrading pytube 10.5.1 -> 10.6.1 solved the issue, the one above is still occuring though.

**Comment by tfdahlin** [comment]
hi @somist this may be related to #947, which I just merged a fix for. See if you can retry the download with the new timeout and max_retries arguments e.g.:
```python
yt = YouTube(url)
yt.streams.get_by_itag(22).download(timeout=10, max_retries=5)
```

**Comment by nanobloom** [comment]
Nothing has changed for this case, still unable to complete the download and behaviour seems to be the same as earlier.

**Comment by tfdahlin** [comment]
y'know, looking at this a little more, i think this is actually a problem on YouTube's side. We ran into this issue (again, with itag 22 specifically) about 6 months ago, but only intermittently on certain videos (see: #839). I'm even running into the same issue when I inspect the web requests being made by youtube itself to find the URLs being accessed with browser tools, and accessing that address by hand.
![image](https://user-images.githubusercontent.com/9667869/113524041-08bbb480-957a-11eb-8998-bbe6cb962d3f.png)


I'm even running into the same issue when I search for the URL and decode it by hand, and looking at the page I'm seeing an error about content-length mismatch:
![image](https://user-images.githubusercontent.com/9667869/113524034-fd688900-9579-11eb-8fc9-bd60dc0805f1.png)

It seems to me that itag 22 might not *actually* exist for this video, even if youtube claims that it does

**Comment by nanobloom** [comment]
Thanks for the explanation, kinda expected it to be on youtube's side.
So if anyone else also happened to run into this issue, the obvious workaround for me was to download non progressive video file and the audio file separately and then merge them with ffmpeg, for example:

ffmpeg -i "videoFile.mp4" -i "audioFile.mp3" -shortest outPutFile.mp4

Guess good enough for a rare issue.
